##--------------------------------------------------------------------------
import pandas as pd
##--------------------------------------------------------------------------
s = pd.Series([1,2,3,4,5],index = ['a','b','c','d','e'])
##--------------------------------------------------------------------------
print (s['f'])
##--------------------------------------------------------------------------
##File "C:\Users\dhanp\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\indexes\base.py", line 3654, in get_loc
##    raise KeyError(key) from err
##KeyError: 'f'
##--------------------------------------------------------------------------
##--------------------------------------------------------------------------
